spring:
  datasource:
    url: jdbc:h2:mem:~/a105
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        show-sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    backend.a105: debug


jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  expiry-seconds: ${JWT_EXPIRY_SECONDS}
  refresh-expiry-seconds: ${JWT_REFRESH_EXPIRY_SECONDS}
auth:
  scheme: "Bearer"
  header: Authorization
oauth:
  kakao:
    client-id: ${KAKAO_REST_API_KEY}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-url: ${KAKAO_REDIRECT_URL} # 프론트 url
    access_token_api: ${KAKAO_TOKEN_API}
    get_userinfo_api: ${KAKAO_USERINFO_API}