server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/app/data/bank-db;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#          show_sql: true
#        format_sql: true
#        use_sql_comments: true
  kafka:
    producer:
#      bootstrap-servers: localhost:10000,localhost:10001,localhost:1000
      bootstrap-servers: Kafka00Service:9092,Kafka01Service:9092,Kafka02Service:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
#      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
      bootstrap-servers: Kafka00Service:9092,Kafka01Service:9092,Kafka02Service:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest