replicaCount: 1

image:
  repository: cheonwoo/linkpay
  tag: backend
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: j12a105.p.ssafy.io
      paths:
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
        - path: /actuator(/|$)(.*)
          pathType: ImplementationSpecific
        - path: /docs(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - host:
        - j12a105.p.ssafy.io
      secretName: j12a105-tls

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

imagePullSecrets:
  - name: docker-hub

# 환경별로 Secret 이름만 바꾸면 되도록 분리
secretName: config-server-credentials
env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev

  - name: SPRING_CONFIG_IMPORT
    value: optional:configserver:http://3.37.114.5:8081

  - name: CONFIG_USERNAME
    valueFrom:
      secretKeyRef:
        name: config-server-credentials
        key: username

  - name: CONFIG_PASSWORD
    valueFrom:
      secretKeyRef:
        name: config-server-credentials
        key: password
