image:
  tag: backend

service:
  type: ClusterIP

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev

  - name: CONFIG_USERNAME
    valueFrom:
      secretKeyRef:
        name: config-server-credentials
        key: username

  - name: CONFIG_PASSWORD
    valueFrom:
      secretKeyRef:
        name: config-server-credentials
        key: password

  - name: SPRING_CONFIG_IMPORT
    value: optional:configserver:http://3.37.114.5:8081

secretName: config-server-credentials

ingress:
  hosts:
    - host: j12a105.p.ssafy.io
      paths:
        - path: /
          pathType: Prefix
